// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTe0WSAfH5nId5VnvLP50nDWUzAfMJkg',
    appId: '1:1005199275104:web:2cdbcd900d82bd4509ff05',
    messagingSenderId: '1005199275104',
    projectId: 'splitwise-931d7',
    authDomain: 'splitwise-931d7.firebaseapp.com',
    storageBucket: 'splitwise-931d7.firebasestorage.app',
    measurementId: 'G-VQPB5K7SPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcT3en4EM99oloWHs4tQv45xHqs2H9cpI',
    appId: '1:1005199275104:android:e7bfc361ce7c402f09ff05',
    messagingSenderId: '1005199275104',
    projectId: 'splitwise-931d7',
    storageBucket: 'splitwise-931d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqWTS0Iz-BZM__qw6tbzBFK8z2rrPX3K8',
    appId: '1:1005199275104:ios:86ab071bd78c891009ff05',
    messagingSenderId: '1005199275104',
    projectId: 'splitwise-931d7',
    storageBucket: 'splitwise-931d7.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqWTS0Iz-BZM__qw6tbzBFK8z2rrPX3K8',
    appId: '1:1005199275104:ios:86ab071bd78c891009ff05',
    messagingSenderId: '1005199275104',
    projectId: 'splitwise-931d7',
    storageBucket: 'splitwise-931d7.firebasestorage.app',
    iosBundleId: 'com.example.splitwiseClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTe0WSAfH5nId5VnvLP50nDWUzAfMJkg',
    appId: '1:1005199275104:web:2301ef2e882bf87209ff05',
    messagingSenderId: '1005199275104',
    projectId: 'splitwise-931d7',
    authDomain: 'splitwise-931d7.firebaseapp.com',
    storageBucket: 'splitwise-931d7.firebasestorage.app',
    measurementId: 'G-YF763FX9V9',
  );
}
